version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_USER: ${DATABASE_USER}
    restart: always
  next:
    build: .
    volumes:
      - next-images:/app/uploaded
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
    restart: always
volumes:
  postgres-data: {}
  next-images: {}
